seed: 2019
dset: office-home
max_epoch: 45
interval: 45
batch_size: 64
net: resnet50
net_mode: fbc 
list_name: image_list_partial # specific for office-home dataset under partial class setting

expname: iclr_2025_formal
key_info: oh_partial_test 

s_model: null 

source: Ar
target: Cl

root: /storage/sfda_lln_extend/DATASOURCE
model_root: /notebooks/sfda_lln_extend/Models/shot
output_dir: /notebooks/sfda_partial/output/iclr_2025_formal
log_dir: /notebooks/sfda_partial/logs/iclr_2025_formal


# lr
lr_decay: True
lr_decay_type: shot 
lr_F_coef: 0.5
lr_power: 0.75


# ==========================================
# ================= Loss ===================
# ==========================================


# --- CL ---
alpha_decay: True
K: 5
beta: 0.75 

# --- CL_NEG_DC ---
dc_loss_type: ce
dc_coef_type: init_incons # fixed or init_incons
dc_coef: 1


# --- CL_POS_PL ---
partial_coef: 0.1
partial_k_type: cal # cal or fixed
partial_k: 2
tau_type: stat # fixed or stat or cal
sample_selection_R: 1.1

# ------------ Evaluation ------------
warmup_eval_iter_num: 10 

